[package]
name = "onerealm"
version = "0.0.1"
edition = "2024.beta"

[environments]
testnet = "4c78adac"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
onerealm = "0x0"
